# python authenticated_query.py -q mutation_query.graphql -u robert

# mutation($mediaId:Int,$status:MediaListStatus){
#     SaveMediaListEntry(mediaId:$mediaId,status:$status,score:$score){
#         status
#         idea
#         score
#     }
# }

# mutation($mediaId:Int,$progress:Int,$status:MediaListStatus){
#     SaveMediaListEntry(mediaId:$mediaId,progress:$progress,status:$status){
#         progress
#         status
#     }
# }
mutation($mediaId:Int,$progress:Int){
    SaveMediaListEntry(mediaId:$mediaId,progress:$progress){
        progress
    }
}

# mutation($mediaId:Int,$progressVolumes:Int,$status:MediaListStatus){
#     SaveMediaListEntry(mediaId:$mediaId,progressVolumes:$progressVolumes,status:$status){
#         progressVolumes
#         status
#     }
# }

# mutation($listEntryId:Int){
#     DeleteMediaListEntry(id:$listEntryId){
#         deleted
#     }
# }

# mutation($listEntryIds:[Int],$status:MediaListStatus){
#     UpdateMediaListEntries(ids:$listEntryIds,status:$status){
#         status
#     }
# }
#
# mutation($mediaId:Int,$notes:String){
#     SaveMediaListEntry(mediaId:$mediaId,notes:$notes){
#         notes
#     }
# }

# mutation($mediaId:Int,$tagId:Int,$vote:Int){
#     SaveMediaTagVote(mediaId:$mediaId,tagId:$tagId,vote:$vote) {
#         mediaId
#         tagId
#         vote
#     }
# }

# mutation(
#     $animeIds: [Int],
#     $mangaIds: [Int],
#     $characterIds: [Int],
#     $staffIds: [Int],
#     $studioIds: [Int],
#     $animeOrder: [Int],
#     $mangaOrder: [Int],
#     $characterOrder: [Int],
#     $staffOrder: [Int],
#     $studioOrder: [Int]
# ) {
#     UpdateFavouriteOrder(
#         animeIds: $animeIds,
#         mangaIds: $mangaIds,
#         characterIds: $characterIds,
#         staffIds: $staffIds,
#         studioIds: $studioIds,
#         animeOrder: $animeOrder,
#         mangaOrder: $mangaOrder,
#         characterOrder: $characterOrder,
#         staffOrder: $staffOrder,
#         studioOrder: $studioOrder
#   ) {
#         anime {
#           pageInfo {
#             total
#       }
#     }
#   }
# }

# mutation(
# #   $animeId: Int,
# #   $mangaId: Int,
# #   $characterId: Int,
# #   $staffId: Int,
# #   $studioId: Int,
# ) {
#     # ToggleFavourite (characterId: $characterId) {
#         # characters {
#     ToggleFavourite (staffId: $staffId) {
#         staff {
#             nodes {
#                 name {
#                     full
#                 }
#             }
#         }
#     }
# }